external_components:
  - source: components/
    components: [ jh_bms_esp32 ]

esphome:
  name: jh-bms-esp32
  friendly_name: JH BMS ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "goodcrop"

ota:
  password: "goodcrop"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jh-Bms-Esp32 Fallback Hotspot"
    password: "fallback_password"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

# JH BMS ESP32组件配置
binary_sensor:
  # 在线状态
  - platform: jh_bms_esp32
    online_status:
      name: "JH BMS Online Status"

  # 充电状态
  - platform: jh_bms_esp32
    charging:
      name: "JH BMS Charging Status"

  # 放电状态
  - platform: jh_bms_esp32
    discharging:
      name: "JH BMS Discharging Status"

  # 均衡状态
  - platform: jh_bms_esp32
    balancing:
      name: "JH BMS Balancing Status"

  # 加热状态
  - platform: jh_bms_esp32
    heating:
      name: "JH BMS Heating Status"

  # 干接点1状态
  - platform: jh_bms_esp32
    dry_contact_1:
      name: "JH BMS Dry Contact 1"

  # 干接点2状态
  - platform: jh_bms_esp32
    dry_contact_2:
      name: "JH BMS Dry Contact 2"

sensor:
  # 总电压
  - platform: jh_bms_esp32
    total_voltage:
      name: "JH BMS Total Voltage"
      accuracy_decimals: 3

  # 电流
  - platform: jh_bms_esp32
    current:
      name: "JH BMS Current"
      accuracy_decimals: 2

  # 功率
  - platform: jh_bms_esp32
    power:
      name: "JH BMS Power"
      accuracy_decimals: 1

  # SOC (荷电状态)
  - platform: jh_bms_esp32
    state_of_charge:
      name: "JH BMS State of Charge"

  # 剩余容量
  - platform: jh_bms_esp32
    capacity_remaining:
      name: "JH BMS Capacity Remaining"
      accuracy_decimals: 3

  # 充电循环次数
  - platform: jh_bms_esp32
    charging_cycles:
      name: "JH BMS Charging Cycles"

  # 温度传感器1
  - platform: jh_bms_esp32
    temperature_sensor_1:
      name: "JH BMS Temperature 1"

  # 温度传感器2
  - platform: jh_bms_esp32
    temperature_sensor_2:
      name: "JH BMS Temperature 2"

  # 电池单体电压（最多支持32个）
  # 根据实际电池数量配置
  - platform: jh_bms_esp32
    cell_voltage_1:
      name: "JH BMS Cell Voltage 1"
      accuracy_decimals: 4

  - platform: jh_bms_esp32
    cell_voltage_2:
      name: "JH BMS Cell Voltage 2"
      accuracy_decimals: 4

  - platform: jh_bms_esp32
    cell_voltage_3:
      name: "JH BMS Cell Voltage 3"
      accuracy_decimals: 4

  # 添加更多电池单体电压传感器...

  # 最小和最大单体电压
  - platform: jh_bms_esp32
    min_cell_voltage:
      name: "JH BMS Min Cell Voltage"
      accuracy_decimals: 4

  - platform: jh_bms_esp32
    max_cell_voltage:
      name: "JH BMS Max Cell Voltage"
      accuracy_decimals: 4

  # 单体电压差
  - platform: jh_bms_esp32
    delta_cell_voltage:
      name: "JH BMS Delta Cell Voltage"
      accuracy_decimals: 4

  # 平均单体电压
  - platform: jh_bms_esp32
    average_cell_voltage:
      name: "JH BMS Average Cell Voltage"
      accuracy_decimals: 4

text_sensor:
  # 错误信息
  - platform: jh_bms_esp32
    errors:
      name: "JH BMS Errors"

  # 操作状态
  - platform: jh_bms_esp32
    operation_status:
      name: "JH BMS Operation Status"

  # 总运行时间（格式化）
  - platform: jh_bms_esp32
    total_runtime_formatted:
      name: "JH BMS Total Runtime"

  # 充电状态
  - platform: jh_bms_esp32
    charge_status:
      name: "JH BMS Charge Status"

# JH BMS ESP32组件主配置
jh_bms_esp32:
  # 设置协议版本：JH01、JH02或JH03
  protocol_version: JH01
  # 设置轮询间隔（10秒）
  throttle: 10s
  # 创建设备连接
  ble_client_id: bms_client

# BLE客户端配置
ble_client:
  - mac_address: "EC:23:09:0D:60:31"  # 替换为您的JH BMS设备的MAC地址
    id: bms_client
    # 连接参数配置
    auto_reconnect: true
    connect_timeout: 30s

# 数值控制配置（用于设置BMS参数）
number:
  # 智能睡眠电压设置
  - platform: jh_bms_esp32
    type: SMART_SLEEP_VOLTAGE
    name: "JH BMS Smart Sleep Voltage"
    min_value: 10.0
    max_value: 60.0
    step: 0.1
    mode: box

  # 单体欠压保护电压设置
  - platform: jh_bms_esp32
    type: CELL_UNDERVOLTAGE_PROTECTION
    name: "JH BMS Cell Undervoltage Protection"
    min_value: 2.5
    max_value: 3.5
    step: 0.01
    mode: box

  # 单体过压保护电压设置
  - platform: jh_bms_esp32
    type: CELL_OVERVOLTAGE_PROTECTION
    name: "JH BMS Cell Overvoltage Protection"
    min_value: 3.6
    max_value: 4.3
    step: 0.01
    mode: box

  # 均衡触发电压设置
  - platform: jh_bms_esp32
    type: BALANCE_TRIGGER_VOLTAGE
    name: "JH BMS Balance Trigger Voltage"
    min_value: 3.2
    max_value: 4.2
    step: 0.01
    mode: box

# 按钮控制配置
button:
  # 检索设置
  - platform: jh_bms_esp32
    type: RETRIEVE_SETTINGS
    name: "JH BMS Retrieve Settings"

  # 检索设备信息
  - platform: jh_bms_esp32
    type: RETRIEVE_DEVICE_INFO
    name: "JH BMS Retrieve Device Info"

  # 保存设置
  - platform: jh_bms_esp32
    type: SAVE_SETTINGS
    name: "JH BMS Save Settings"

  # 清除错误
  - platform: jh_bms_esp32
    type: CLEAR_ERRORS
    name: "JH BMS Clear Errors"

# 开关控制配置
switch:
  # 充电开关
  - platform: jh_bms_esp32
    type: CHARGING
    name: "JH BMS Charging Switch"

  # 放电开关
  - platform: jh_bms_esp32
    type: DISCHARGING
    name: "JH BMS Discharging Switch"

  # 均衡器开关
  - platform: jh_bms_esp32
    type: BALANCER
    name: "JH BMS Balancer Switch"

  # 加热开关
  - platform: jh_bms_esp32
    type: HEATING
    name: "JH BMS Heating Switch"