substitutions:
  name: jh-bms-monitor
  device_description: "JH BMS Monitor for ESP32"
  external_components_source: github://goodcrop79/esphome-jh-bms@main

esphome:
  name: ${name}
  comment: ${device_description}
  friendly_name: ${name}
  platformio_options:
    board_build.f_cpu: 240000000L

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "YourEncryptionKeyHere"

ota:
  password: "YourOTAPasswordHere"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback"
    password: "FallbackPassword"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    active: true

# 使用外部组件
external_components:
  - source: ${external_components_source}
    components: [jh_bms_esp32]
    refresh: 1d

# JH BMS组件配置
jh_bms_esp32:
  id: my_jh_bms
  update_interval: 10s

# 电池电压传感器
sensor:
  - platform: jh_bms_esp32
    id: ${name}_battery_voltage
    type: battery_voltage
    name: "${name} Battery Voltage"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 2
    unit_of_measurement: V

  # 电池电流传感器
  - platform: jh_bms_esp32
    id: ${name}_battery_current
    type: battery_current
    name: "${name} Battery Current"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    unit_of_measurement: A

  # 电池温度传感器
  - platform: jh_bms_esp32
    id: ${name}_battery_temperature
    type: battery_temperature
    name: "${name} Battery Temperature"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    unit_of_measurement: °C

  # SOC (State of Charge) 传感器
  - platform: jh_bms_esp32
    id: ${name}_battery_soc
    type: state_of_charge
    name: "${name} Battery SOC"
    device_class: battery
    state_class: measurement
    accuracy_decimals: 0
    unit_of_measurement: "%"

# 电池状态二进制传感器
binary_sensor:
  - platform: jh_bms_esp32
    id: ${name}_charging_status
    type: charging_status
    name: "${name} Charging Status"
    device_class: battery_charging