# 使用本地组件方式 - 这是目前最可靠的解决方案
# 通过GitHub拉取JH BMS组件（包含修复代码的版本1.0.19）
# 已完全修复ESPHome 2025.9.3版本的所有导入错误、循环导入问题和命名空间变量不匹配问题
# 修复包括CONF_NUMBERS、CONF_BUTTONS、CONF_PROTOCOL_VERSION、UNIT_MILLIOHM和UNIT_AMPERE_HOURS的缺失定义，以及所有命名空间变量名的统一
# 添加了number.number_schema()函数的兼容性补丁，解决了ESPHome 2025.9.3版本中的API变化问题
# 修复了所有组件中使用的图标常量导入错误，特别是button模块中遗漏的图标常量
# 添加了缺失的sensor和binary_sensor模块导入，解决了'name 'sensor' is not defined'错误
# 修复了sensor.sensor和binary_sensor.binary_sensor属性名错误，更新为sensor.Sensor和binary_sensor.BinarySensor，解决了ESPHome 2025.9.3版本中的AttributeError错误
# 添加了缺失的text_sensor模块导入，解决了'name 'text_sensor' is not defined'错误
# 修复了text_sensor.text_sensor属性名错误，更新为text_sensor.TextSensor，解决了ESPHome 2025.9.3版本中的属性名错误
# 修复了button.jh_button_schema属性名错误，更新为button.CONFIG_SCHEMA，解决了ESPHome 2025.9.3版本中的AttributeError错误
# 修复了polling_component_schema参数类型错误，将数字1000更新为字符串"1s"，解决了ESPHome 2025.9.3版本中的AssertionError错误
# 1.0.24 - 修复throttle参数的cv.Range配置在ESPHome 2025.10.0版本中的类型兼容性错误

substitutions:
  name: jh-bms-monitor
  device_description: "Monitor and control a JH-BMS via bluetooth"

# 通过GitHub拉取组件
# 推荐使用此方式，方便后期修改代码后重新上传GitHub并获取更新
external_components:
  # JH BMS组件
  - source: github://goodcrop79/esphome-jh-bms@main
    components: [jh_bms_esp32]
    refresh: 0s  # 设置为0s可以立即获取最新代码，修改后设置回1d
esphome:
  name: ${name}
  friendly_name: JH BMS Monitor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "XauRqb0rKYuGp42N8w0JiTOFBg32TwWkm7cUnsTR00c="

ota:
  platform: esphome
  password: "goodcrop"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jh-Bms-Monitor Fallback Hotspot"
    password: "fallback_password"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

# JH BMS ESP32组件主配置
jh_bms_esp32:
  # 只有1个版本，不需要设置协议版本
  # 设置轮询间隔（10秒）
  throttle: 10s
  # 创建设备连接
  ble_client_id: bms_client

# BLE客户端配置
ble_client:
  - mac_address: "EC:23:09:0D:60:31"  # 替换为您的JH BMS设备的MAC地址
    id: bms_client
    # 连接参数配置
    auto_reconnect: true
    connect_timeout: 30s

# 二进制传感器配置
binary_sensor:
  # 在线状态
  - platform: jh_bms_esp32
    online_status:
      name: "JH BMS Online Status"

  # 充电状态
  - platform: jh_bms_esp32
    charging:
      name: "JH BMS Charging Status"

  # 放电状态
  - platform: jh_bms_esp32
    discharging:
      name: "JH BMS Discharging Status"

  # 均衡状态
  - platform: jh_bms_esp32
    balancing:
      name: "JH BMS Balancing Status"

# 传感器配置
sensor:
  # 总电压
  - platform: jh_bms_esp32
    total_voltage:
      name: "JH BMS Total Voltage"
      accuracy_decimals: 3

  # 电流
  - platform: jh_bms_esp32
    current:
      name: "JH BMS Current"
      accuracy_decimals: 2

  # SOC (荷电状态)
  - platform: jh_bms_esp32
    state_of_charge:
      name: "JH BMS State of Charge"

  # 温度传感器1
  - platform: jh_bms_esp32
    temperature_sensor_1:
      name: "JH BMS Temperature 1"

  # 温度传感器2
  - platform: jh_bms_esp32
    temperature_sensor_2:
      name: "JH BMS Temperature 2"

# 文本传感器配置
text_sensor:
  # 错误信息
  - platform: jh_bms_esp32
    errors:
      name: "JH BMS Errors"

  # 操作状态
  - platform: jh_bms_esp32
    operation_status:
      name: "JH BMS Operation Status"